Fix AttributeError: module 'modal' has no attribute 'Mount'
- Replaced deprecated `modal.Mount.from_local_dir` with `modal.Image.debian_slim().add_local_dir("src", remote_path="/root/src")`
- Added `test_run_cloud.py` to test importing the deployment script, ensuring changes in modal API don't break our CI deployments without us noticing.

Co-authored-by: japppie <131072659+japppie@users.noreply.github.com>